version: 2

updates:
  - package-ecosystem: cargo
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    commit-message:
      prefix: "deps(cargo)"

  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: "weekly"
    target-branch: "dev"
    commit-message:
      prefix: "deps(ci)"
