[package]
name = "scanner"
version = "0.3.0"
authors.workspace = true
edition.workspace = true
build = "build.rs"

[lints]
workspace = true

[dependencies]
blueprint.workspace = true
clap.workspace = true
error-stack = "0.4"
factorio_api = { workspace = true, features = ["blocking"] }
flate2.workspace = true
image.workspace = true
log.workspace = true
locale.workspace = true
mod_util = { workspace = true, features = ["bp_meta_info"] }
pretty_logging.workspace = true
prototypes.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
thiserror.workspace = true
types.workspace = true
dotenv = "0.15"
rustc-hash = "1.1"
tokio = "1.35"
capnp = "0.19"
actix-web = "4.4"
actix-web-actors = "4.2"
actix = "0.13"
strum = { version = "0.25", features = ["derive"] }

[build-dependencies]
capnpc = "0.19.0"
