[package]
name = "scanner"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow.workspace = true
blueprint.workspace = true
clap.workspace = true
factorio_api = { workspace = true, features = ["blocking"] }
image.workspace = true
locale.workspace = true
mod_util = { workspace = true, features = ["bp_meta_info"] }
prototypes.workspace = true
serde.workspace = true
serde_json.workspace = true
serde_with.workspace = true
types.workspace = true
