[package]
name = "scanner"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
blueprint.workspace = true
clap.workspace = true
image.workspace = true
locale.workspace = true
mod_util.workspace = true
prototypes.workspace = true
serde.workspace = true
serde_json.workspace = true
types.workspace = true
