[package]
name = "blueprint"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
base64 = "0.21.4"
flate2 = "1.0.27"
serde.workspace = true
serde_helper.workspace = true
serde_json.workspace = true
serde_with.workspace = true
types.workspace = true
