[package]
name = "types"
version = "1.1.101"
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
anyhow.workspace = true
image.workspace = true
konst.workspace = true
mod_util.workspace = true
regex = "1.10.0"
serde.workspace = true
serde_helper.workspace = true
serde_repr.workspace = true
serde_with.workspace = true
