[package]
name = "serde_helper"
version = "0.1.0"
authors.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
num = "0.4"
paste.workspace = true
serde.workspace = true
